#!/usr/bin/env python3
"""Regenerate probabilies_post_sigmaclip.pdf and ngc6383_mass_binary.pdf with
the accessible viridis colormap (replacing coolwarm/coolwarm_r), matching the
notebook layout. Data from saved CDS table + ASteCA output (no pipeline re-run)."""
import numpy as np, pandas as pd
from astropy.table import Table
import matplotlib; matplotlib.use("Agg")
matplotlib.rcParams.update({"xtick.labelsize": 13, "ytick.labelsize": 13, "axes.labelsize": 15, "legend.fontsize": 11, "axes.titlesize": 14})
import matplotlib.pyplot as plt

B="/Users/notluquis/erotica/data/test/NGC6383"
FIG=f"{B}/comments_paper/submission_package/clean_source/Figures/"

# ---------- probabilities (Fig 1): p_tilde vs G coloured by fidelity ----------
m=Table.read(f"{B}/comments_paper/cds_final/ngc6383_members.ecsv").to_pandas()
fig,ax=plt.subplots(figsize=(7,6),layout="tight")
sc=ax.scatter(m.Gmag,m.pMember,s=9,c=m.Fidelity,cmap="viridis",vmin=m.Fidelity.min(),vmax=m.Fidelity.max())
cb=fig.colorbar(sc,pad=0.01); cb.set_label("Astrometric fidelity",fontsize=14)
ax.axhline(0.6,color="k",ls="--",lw=1,label=r"$\tilde{p}=0.6$")
ax.axhline(0.8,color="k",ls=":",lw=1,label=r"$\tilde{p}=0.8$")
ax.set_xlabel(r"$G$ [mag]",fontsize=15); ax.set_ylabel(r"Membership pseudo-probability $\tilde{p}$",fontsize=15)
ax.legend(loc="lower left",fontsize=11)
fig.savefig(FIG+"probabilies_post_sigmaclip.pdf",bbox_inches="tight"); plt.close()
print("wrote probabilies_post_sigmaclip.pdf  (N=%d, viridis)"%len(m))

# ---------- mass-binary CMD: coloured by total mass / binary prob ----------
ast=pd.read_csv(f"{B}/ASteCA/output/NGC_6383_dr3_all/NGC_6383_dr3_all.csv",sep=r"\s+").reset_index(drop=True)
ms=pd.read_csv(f"{B}/data/40/masses_asteca_069.csv")
bp=ms.binar_prob.values
mass=ms.m1.values+np.where(bp>0.7,np.nan_to_num(ms.m2.values),0.0)
G=ast.Gmag.values; BPRP=ast.BP_RP.values
# clean mode-fit isochrone locus saved by regen_cmd_figs.py (smooth single-star
# sequence from asteca get_isochrone, already ordered along the isochrone). This
# replaces the previous practice of connecting the scattered synthetic sample,
# which produced a non-physical side-to-side zig-zag at faint magnitudes.
_loc=np.load(f"{FIG}mode_locus.npz"); iso_g=_loc["G"]; iso_bprp=_loc["bprp"]

fig,axs=plt.subplots(2,1,figsize=(8,14))
for ax,(c,lab,cm) in zip(axs,[(mass,r"Total mass $[M_\odot]$","viridis_r"),(bp,"Binary probability","viridis_r")]):
    ax.plot(iso_bprp,iso_g,color="0.3",ls="--",lw=1.2,zorder=1,label="Best mode-fit isochrone")
    s=ax.scatter(BPRP,G,s=80,lw=0,marker="*",c=c,cmap=cm,zorder=5)
    cb=fig.colorbar(s,ax=ax,pad=0.01); cb.set_label(lab,fontsize=13)
    ax.invert_yaxis(); ax.set_xlabel(r"$G_{\mathrm{BP}}-G_{\mathrm{RP}}$ [mag]",fontsize=14); ax.set_ylabel(r"$G$ [mag]",fontsize=14)
    ax.legend(loc="upper right")
fig.savefig(FIG+"ngc6383_mass_binary.pdf",bbox_inches="tight"); plt.close()
print("wrote ngc6383_mass_binary.pdf  (N=%d, viridis_r)"%len(ast))

# NOTE: center_determination_paper.pdf is generated by regen_center.py
# (matches the notebook's graph_center_determination, incl. the 5 pc scale bar).
from scipy.stats import multivariate_normal
ra=m.RAdeg.values; dec=m.DEdeg.values; ptil=m.pMember.values

# ---------- proper motion: PM scatter coloured by p, fitted 2D Gaussian contours ----------
pmra=m.pmRA.values; pmdec=m.pmDE.values
cpmra,cpmdec=2.542,-1.713
fig,ax=plt.subplots(figsize=(7.5,6.5))
mu=[2.542,-1.713]  # published fitted PM model (254-source reference sample)
cov=np.array([[0.152**2,0.014*0.152*0.138],[0.014*0.152*0.138,0.138**2]])
# grid spans the data and the 3-sigma model extent (whichever is wider) so the
# 3-sigma ellipse is fully drawn instead of clipped at the data range
sx,sy=np.sqrt(cov[0,0]),np.sqrt(cov[1,1])
gxlo,gxhi=min(pmra.min(),mu[0]-3.5*sx),max(pmra.max(),mu[0]+3.5*sx)
gylo,gyhi=min(pmdec.min(),mu[1]-3.5*sy),max(pmdec.max(),mu[1]+3.5*sy)
gx,gy=np.mgrid[gxlo:gxhi:200j,gylo:gyhi:200j]
rv=multivariate_normal(mu,cov); gz=rv.pdf(np.dstack([gx,gy]))
# 1,2,3-sigma iso-probability ellipses (standard for a 2D Gaussian): the k-sigma
# contour sits at pdf_peak*exp(-k^2/2); the 3-sigma ellipse spans the full member
# spread (instead of many auto-levels bunched near the peak, which looked too small)
peak=rv.pdf(mu); slev=sorted(peak*np.exp(-np.array([3.0,2.0,1.0])**2/2))
ax.contour(gx,gy,gz,levels=slev,colors="0.4",linewidths=0.8,zorder=2)
sc=ax.scatter(pmra,pmdec,c=ptil,cmap="viridis",s=12,zorder=3)
ax.axvline(cpmra,color="darkorange",ls="--",lw=1.6,zorder=4,label="Center"); ax.axhline(cpmdec,color="darkorange",ls="--",lw=1.6,zorder=4)
ax.scatter([cpmra],[cpmdec],marker="+",s=240,color="blue",lw=2.2,zorder=5,label=r"$C=(2.542,-1.713)$")
from matplotlib.lines import Line2D
_ellproxy=Line2D([0],[0],color="0.4",lw=0.8,label=r"$1\sigma,2\sigma,3\sigma$ Gaussian contours")
cb=fig.colorbar(sc,ax=ax,pad=0.01); cb.set_label(r"Membership pseudo-probability $\tilde{p}$",fontsize=13)
ax.set_xlabel(r"$\mu_{\alpha}^{*}$ [mas yr$^{-1}$]",fontsize=14); ax.set_ylabel(r"$\mu_{\delta}$ [mas yr$^{-1}$]",fontsize=14)
h,_=ax.get_legend_handles_labels(); ax.legend(handles=h+[_ellproxy],loc="upper left")
ax.use_sticky_edges=False; ax.margins(0.05)  # contour pins limits via sticky edges; disable so the default 5% data margin applies (no point on the frame)
fig.savefig(FIG+"proper_motion_2d_paper.pdf",bbox_inches="tight"); plt.close()
print("wrote proper_motion_2d_paper.pdf  (viridis + 2D Gaussian)")
